version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: ../infrastructure/docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
      - VITE_WS_URL=ws://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - cloud-ide-network

  # Backend API Service  
  backend:
    build:
      context: ./backend
      dockerfile: ../infrastructure/docker/backend.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - workspace:/workspace
    networks:
      - cloud-ide-network

  # Development Environment Container
  dev-environment:
    build:
      context: ./dev-container
      dockerfile: ./Dockerfile
    volumes:
      - workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WORKSPACE_PATH=/workspace
    networks:
      - cloud-ide-network
    tty: true
    stdin_open: true

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - cloud-ide-network
    profiles:
      - production

volumes:
  workspace:
    driver: local

networks:
  cloud-ide-network:
    driver: bridge